name: Build

on: [push, pull_request]

jobs:
  build-binary:
    name: Build payloads
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build payloads
      run: |
        docker build -t payloadsbuilder .
        docker run --rm -v ${PWD}:/project payloadsbuilder make -C rpx_replacement
    - uses: actions/upload-artifact@v2
      with:
       name: payloads
       path: "**/recovery_menu"
